[project]
name = "recherche"
version = "0.1.0"
description = "Projet 1 du cours d'IA (INFO-F-311). Recherche sur des graphes."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["laser-learning-environment>=1.3.2", "pytest>=8.3.3"]


[tool.pytest.ini_options]
pythonpath = ["src"]
